"""Phase 7 — LightGBM + RandomizedSearchCV on train; MLflow; persist best params."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import joblib
import mlflow
import mlflow.sklearn
import pandas as pd
import yaml
from lightgbm import LGBMClassifier
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from sklearn.pipeline import Pipeline

from churn_ml.features.pipeline import build_feature_pipeline, select_feature_matrix
from churn_ml.models.baseline import compute_val_metrics, default_tracking_uri, y_positive_binary


def load_tune_lightgbm_config(path: Path) -> dict[str, Any]:
    with Path(path).open(encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    if not isinstance(cfg, dict):
        raise ValueError("tune_lightgbm config must be a YAML mapping")
    for key in ("random_state", "cv", "scoring", "lightgbm", "param_distributions", "mlflow", "outputs"):
        if key not in cfg:
            raise ValueError(f"tune_lightgbm config missing required key: {key}")
    if not isinstance(cfg["mlflow"], dict) or "experiment_name" not in cfg["mlflow"]:
        raise ValueError("mlflow.experiment_name is required")
    if not isinstance(cfg["outputs"], dict):
        raise ValueError("outputs must be a mapping")
    return cfg


def _to_scalar(v: Any) -> Any:
    if hasattr(v, "item"):
        return v.item()
    return v


def build_lightgbm_pipeline(feat_cfg: dict[str, Any], tune_cfg: dict[str, Any]) -> Pipeline:
    """Same preprocess as baseline; LGBMClassifier with fixed kwargs from config."""
    prep = build_feature_pipeline(feat_cfg)
    ct = prep.named_steps["preprocess"]
    lgbm_kw = dict(tune_cfg["lightgbm"])
    lgbm_kw["random_state"] = int(tune_cfg["random_state"])
    clf = LGBMClassifier(**lgbm_kw)
    return Pipeline([("preprocess", ct), ("classifier", clf)])


def _best_lgbm_params(search: RandomizedSearchCV) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for k, v in search.best_params_.items():
        if k.startswith("classifier__"):
            out[k.replace("classifier__", "")] = _to_scalar(v)
    return out


def _write_best_config(
    path: Path,
    *,
    tune_cfg_path: Path,
    tune_cfg: dict[str, Any],
    search: RandomizedSearchCV,
    val_metrics: dict[str, float],
) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    best = _best_lgbm_params(search)
    doc = {
        "_generated": datetime.now(timezone.utc).isoformat(),
        "_source_tune_config": str(tune_cfg_path.as_posix()),
        "cv_best_mean_roc_auc": float(search.best_score_),
        "validation_metrics": {k: float(v) for k, v in val_metrics.items()},
        "lightgbm": {**dict(tune_cfg["lightgbm"]), **best},
    }
    with path.open("w", encoding="utf-8") as f:
        f.write("# Auto-generated by Phase 7 (churn-train-lightgbm). Do not edit blindly.\n")
        yaml.safe_dump(doc, f, sort_keys=False, default_flow_style=False)


def train_lightgbm_tuned(
    train_df: pd.DataFrame,
    val_df: pd.DataFrame,
    feat_cfg: dict[str, Any],
    tune_cfg: dict[str, Any],
    *,
    tune_cfg_path: Path,
    output_path: Path,
    best_config_path: Path,
    tracking_uri: str | None = None,
) -> tuple[Pipeline, dict[str, float], RandomizedSearchCV]:
    """Stratified CV on train, refit best; validation metrics; MLflow parent + nested trial runs."""
    uri = tracking_uri if tracking_uri is not None else default_tracking_uri()
    mlflow.set_tracking_uri(uri)

    X_tr = select_feature_matrix(train_df, feat_cfg)
    y_tr = y_positive_binary(train_df)
    X_va = select_feature_matrix(val_df, feat_cfg)
    y_va = y_positive_binary(val_df)

    pipe = build_lightgbm_pipeline(feat_cfg, tune_cfg)
    cv_cfg = tune_cfg["cv"]
    cv = StratifiedKFold(
        n_splits=int(cv_cfg["n_splits"]),
        shuffle=bool(cv_cfg.get("shuffle", True)),
        random_state=int(tune_cfg["random_state"]),
    )
    search = RandomizedSearchCV(
        estimator=pipe,
        param_distributions=dict(tune_cfg["param_distributions"]),
        n_iter=int(cv_cfg["n_iter"]),
        scoring=str(tune_cfg["scoring"]),
        cv=cv,
        refit=True,
        random_state=int(tune_cfg["random_state"]),
        n_jobs=-1,
        verbose=0,
    )
    search.fit(X_tr, y_tr)

    best_pipe: Pipeline = search.best_estimator_
    val_metrics = compute_val_metrics(best_pipe, X_va, y_va)

    mf = tune_cfg["mlflow"]
    experiment_name = str(mf["experiment_name"])
    run_name = str(mf.get("run_name") or "lightgbm_random_search")
    mlflow.set_experiment(experiment_name)

    with mlflow.start_run(run_name=run_name):
        mlflow.set_tag("model_family", "lightgbm")
        mlflow.set_tag("phase", "7_lightgbm_tuning")
        mlflow.log_param("n_train", len(train_df))
        mlflow.log_param("n_val", len(val_df))
        mlflow.log_param("cv_n_splits", int(cv_cfg["n_splits"]))
        mlflow.log_param("search_n_iter", int(cv_cfg["n_iter"]))
        mlflow.log_param("scoring", str(tune_cfg["scoring"]))
        mlflow.log_metric("cv_best_mean_roc_auc", float(search.best_score_))

        cv_res = search.cv_results_
        n_candidates = len(cv_res["params"])
        for i in range(n_candidates):
            with mlflow.start_run(nested=True, run_name=f"trial_{i + 1}"):
                for pk, pv in cv_res["params"][i].items():
                    short = pk.replace("classifier__", "lgbm_")
                    mlflow.log_param(short, _to_scalar(pv))
                mlflow.log_metric("cv_mean_roc_auc", float(cv_res["mean_test_score"][i]))
                mlflow.log_metric("cv_std_roc_auc", float(cv_res["std_test_score"][i]))

        for k, v in _best_lgbm_params(search).items():
            mlflow.log_param(f"best_lgbm_{k}", _to_scalar(v))
        for k, v in val_metrics.items():
            mlflow.log_metric(k, v)

        mlflow.sklearn.log_model(best_pipe, artifact_path="sklearn-model")
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(best_pipe, out)
        mlflow.log_artifact(str(out), artifact_path="lightgbm-joblib")

    _write_best_config(
        best_config_path,
        tune_cfg_path=tune_cfg_path,
        tune_cfg=tune_cfg,
        search=search,
        val_metrics=val_metrics,
    )

    return best_pipe, val_metrics, search
