"""Compute EDA tables and write JSON, Markdown, and figures (no profiling libraries)."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from churn_ml.data.validate import load_raw_csv, validate_raw_dataframe
from churn_ml.metrics import negative_class_label, positive_class_label, target_column


def _encode_target(series: pd.Series) -> pd.Series:
    pos, neg = positive_class_label(), negative_class_label()
    return series.map({pos: 1, neg: 0})


def build_eda_summary(df: pd.DataFrame) -> dict[str, Any]:
    """Structured summary for JSON export and Markdown rendering."""
    tgt = target_column()
    y = _encode_target(df[tgt])
    n = len(df)
    churn_counts = df[tgt].value_counts(dropna=False)
    churn_pct = (df[tgt] == positive_class_label()).mean() * 100

    missing = df.isna().sum()
    missing_pct = (missing / n * 100).round(2)
    miss_df = (
        pd.DataFrame({"missing_count": missing, "missing_pct": missing_pct})
        .query("missing_count > 0")
        .sort_values("missing_count", ascending=False)
    )
    if len(miss_df) > 0:
        missing_serializable = {
            "missing_count": miss_df["missing_count"].astype(int).to_dict(),
            "missing_pct": miss_df["missing_pct"].astype(float).to_dict(),
        }
    else:
        missing_serializable = {}

    cat_cols = df.select_dtypes(include=["object", "string", "category"]).columns.tolist()
    if tgt in cat_cols:
        cat_cols = [c for c in cat_cols if c != tgt]
    cardinalities = {c: int(df[c].nunique(dropna=False)) for c in cat_cols}

    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    corrs: dict[str, float] = {}
    for c in num_cols:
        if c == tgt:
            continue
        s = pd.to_numeric(df[c], errors="coerce")
        mask = s.notna() & y.notna()
        if mask.sum() < 2 or s[mask].std() == 0:
            continue
        corrs[c] = float(s[mask].corr(y[mask]))

    corrs_sorted = dict(sorted(corrs.items(), key=lambda x: abs(x[1]), reverse=True)[:15])

    return {
        "n_rows": int(n),
        "n_columns": int(df.shape[1]),
        "target_column": tgt,
        "churn_rate_pct_positive": round(float(churn_pct), 3),
        "churn_value_counts": {str(k): int(v) for k, v in churn_counts.items()},
        "missing_by_column": missing_serializable,
        "categorical_cardinality": cardinalities,
        "numeric_correlation_with_churn_top": corrs_sorted,
        "columns_list": list(df.columns),
    }


def _markdown_report(summary: dict[str, Any]) -> str:
    lines = [
        "# EDA summary — Telco churn",
        "",
        "Generated by `churn_ml.eda` (Phase 3). **Stratify train/val/test on `Churn` in Phase 4.**",
        "",
        "## Target (`Churn`)",
        "",
        f"- Rows: **{summary['n_rows']}**",
        f"- Positive rate (`{positive_class_label()}`): **{summary['churn_rate_pct_positive']}%**",
        "",
        "| Value | Count |",
        "|-------|-------|",
    ]
    for k, v in summary["churn_value_counts"].items():
        lines.append(f"| {k} | {v} |")
    lines.extend(
        [
            "",
            "*Figure `figures/churn_distribution.png`*: labels on each bar = **count** and **% of all rows**; left Y-axis removed (no side tick marks — values read from labels).",
            "",
            "## Missing values",
            "",
        ]
    )
    miss = summary.get("missing_by_column") or {}
    if not miss.get("missing_count"):
        lines.append("No missing values after load/coercion.")
    else:
        lines.append("| Column | Count | Pct |")
        lines.append("|--------|-------|-----|")
        mc = miss["missing_count"]
        mp = miss["missing_pct"]
        for col in sorted(mc.keys(), key=lambda c: mc[c], reverse=True):
            lines.append(f"| {col} | {mc[col]} | {mp[col]} |")
        lines.extend(
            [
                "",
                "*Figure `figures/missingness_top.png`*: only columns with ≥1 missing cell. Bar length = **absolute** missing count; text = **count (% of all rows)**. Use this as a **data-quality gate** before Phase 4 (imputation rules). With Telco, expect almost only `TotalCharges` (new accounts, `tenure == 0`).",
                "",
            ]
        )
    lines.extend(["", "## Categorical cardinality (encoding hints)", ""])
    lines.append("| Column | N unique |")
    lines.append("|--------|----------|")
    for c, k in sorted(summary["categorical_cardinality"].items(), key=lambda x: -x[1])[:20]:
        lines.append(f"| {c} | {k} |")
    lines.extend(["", "## Numeric features vs churn (Pearson)", ""])
    if not summary["numeric_correlation_with_churn_top"]:
        lines.append("_No numeric correlations computed._")
    else:
        lines.append("| Feature | Correlation |")
        lines.append("|---------|-------------|")
        for c, r in summary["numeric_correlation_with_churn_top"].items():
            lines.append(f"| {c} | {r:.4f} |")
    lines.extend(
        [
            "",
            "## Modeling notes (from EDA)",
            "",
            "- Drop **`customerID`** for training (identifier, high cardinality).",
            "- Several columns are categorical strings (`Yes`/`No`, `InternetService`, etc.) — use one-hot or similar in Phase 5.",
            "- **`TotalCharges`** missing values (often `tenure == 0`): impute or derive in Phase 4.",
            "- See **`docs/EDA_LEAKAGE_CHECKLIST.md`** for leakage review.",
            "",
        ]
    )
    return "\n".join(lines)


def write_eda_artifacts(df: pd.DataFrame, output_dir: Path) -> dict[str, Path]:
    """Write `eda_summary.json`, `eda_summary.md`, and figures under `output_dir`."""
    output_dir = Path(output_dir)
    fig_dir = output_dir / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)

    summary = build_eda_summary(df)

    json_path = output_dir / "eda_summary.json"
    json_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    md_path = output_dir / "eda_summary.md"
    md_path.write_text(_markdown_report(summary), encoding="utf-8")

    tgt = target_column()
    neg, pos = negative_class_label(), positive_class_label()
    order = [neg, pos]
    c_series = df[tgt].value_counts().reindex(order, fill_value=0)
    n_total = int(c_series.sum())
    pcts = c_series / n_total * 100 if n_total else c_series * 0

    fig, ax = plt.subplots(figsize=(5, 4))
    x = np.arange(len(order))
    colors = ["#4C72B0", "#DD8452"]
    bars = ax.bar(x, c_series.values, color=colors, edgecolor="black", width=0.55)
    for bar, cnt, pct in zip(bars, c_series.values, pcts.values):
        lbl = f"{int(cnt):,}\n({pct:.1f}%)"
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height(),
            lbl,
            ha="center",
            va="bottom",
            fontsize=10,
            linespacing=1.15,
        )
    ax.set_xticks(x)
    ax.set_xticklabels(order)
    ax.set_title("Churn class distribution")
    ax.set_xlabel(tgt)
    ymax = float(c_series.max()) * 1.32 if n_total else 1.0
    ax.set_ylim(0, max(ymax, 1.0))
    for spine in ("top", "right", "left"):
        ax.spines[spine].set_visible(False)
    ax.tick_params(axis="y", left=False, labelleft=False)
    ax.set_ylabel("")
    fig.tight_layout()
    churn_fig = fig_dir / "churn_distribution.png"
    fig.savefig(churn_fig, dpi=120)
    plt.close(fig)

    out_paths: dict[str, Path] = {
        "json": json_path,
        "markdown": md_path,
        "churn_figure": churn_fig,
    }
    miss = summary.get("missing_by_column") or {}
    mc = miss.get("missing_count") or {}
    if mc:
        n_rows = max(int(summary["n_rows"]), 1)
        cols = sorted(mc.keys(), key=lambda c: mc[c], reverse=True)[:15]
        vals = [int(mc[c]) for c in cols]
        pcts = [100.0 * v / n_rows for v in vals]
        fig_h = max(2.8, 0.42 * len(cols))
        fig, ax = plt.subplots(figsize=(7.5, fig_h))
        y_pos = np.arange(len(cols))
        bars = ax.barh(y_pos, vals, color="#55A868", edgecolor="#333333", linewidth=0.4, height=0.65)
        xmax = max(vals) if vals else 1
        pad = max(xmax * 0.08, 0.5)
        for y, v, pct in zip(y_pos, vals, pcts):
            ax.text(
                v + pad,
                y,
                f"{v:,}  ({pct:.2f}%)",
                va="center",
                ha="left",
                fontsize=9,
            )
        ax.set_yticks(y_pos)
        ax.set_yticklabels(cols)
        ax.set_xlim(0, xmax + pad + xmax * 0.35)
        ax.set_title("Missing values by column (raw after load)")
        ax.set_xlabel("Missing row count")
        for spine in ("top", "right"):
            ax.spines[spine].set_visible(False)
        fig.tight_layout()
        miss_fig = fig_dir / "missingness_top.png"
        fig.savefig(miss_fig, dpi=120)
        plt.close(fig)
        out_paths["missingness_figure"] = miss_fig

    return out_paths


def run_eda_pipeline(input_csv: Path, output_dir: Path, skip_validation: bool = False) -> dict[str, Path]:
    """Load CSV, optionally validate schema, write all EDA artifacts."""
    df = load_raw_csv(Path(input_csv))
    if not skip_validation:
        df = validate_raw_dataframe(df)
    return write_eda_artifacts(df, output_dir)
